dist: trusty
language: cpp
sudo: required
compiler: gcc
services:
- docker

before_install:
- sudo apt-add-repository -y ppa:wdconinc/ppa-trusty
- sudo apt-get update -y
- sudo apt-get install -y cmake3 root-system libgeant4-dev
- sudo install-geant4-data all 2>&1 | grep -v -F ".........."

script:
- mkdir build ;
  pushd build ;
  cmake .. 2>&1 | tee -a ../remollbuild.log ;
  make     2>&1 | tee -a ../remollbuild.log ;
  popd ;
- mkdir map_directory ;
  wget --directory-prefix=map_directory http://hallaweb.jlab.org/12GeV/Moller/downloads/remoll/blockyHybrid_rm_3.0.txt 2>&1 | grep -v -F ".........." ;
  wget --directory-prefix=map_directory http://hallaweb.jlab.org/12GeV/Moller/downloads/remoll/blockyUpstream_rm_1.1.txt 2>&1 | grep -v -F ".........." ;
- source geant4.sh ;
  for suite in unit commit release ; do
    scripts/tests/test_macros.sh ${suite} 2>&1 | tee remolltest.${suite}.log ;
    tar -czvf remolltest.${suite}.log.tar.gz		-C logfiles/tests	${suite}/*.log
    tar -czvf remolltest.${suite}.analysis.log.tar.gz	-C logfiles/tests	${suite}/analysis/*.log ;
    tar -czvf remolltest.${suite}.root.tar.gz		-C rootfiles/tests	${suite}/*.root ;
    tar -czvf remolltest.${suite}.analysis.png.tar.gz	-C rootfiles/tests	${suite}/analysis/*.png ;
    tar -czvf remolltest.${suite}.analysis.root.tar.gz	-C rootfiles/tests	${suite}/analysis/*.root ;
  done ;
- docker build -t jeffersonlab/remoll .

after_success:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
- if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag jeffersonlab/remoll jeffersonlab/remoll:latest && docker push jeffersonlab/remoll:latest;
  else
    docker tag jeffersonlab/remoll jeffersonlab/remoll:$TRAVIS_BRANCH && docker push jeffersonlab/remoll:$TRAVIS_BRANCH;
  fi

deploy:
  provider: releases
  api_key:
    secure: MzvvPA8KxYjEVa8C9rNtAQbtD+mDx2Wn3Em02JKMtwv953Htnv3zRcyGPfF++sLV80RvZ8NZ8pN3WfiAPTBHatUSgWh9w+GRv0G366wxKrAS4O+9BVy96U7A0gFkaXRwXirJWo4u2lJscQ1hC2IDbI2dGAS/VF5Lt1TLjWcPUL8LPcKgF80FG8+9+BUH1cRiW8mULT36EeVAB1K+vwO6Qob5k4ef66eHjkbdpuUktDr6wrehoyGXtFiBfl+XWotvcrer/51J6wn85UqCc/A+KYrVshBH/gKCD7/w6D2akNM2/sJcFdLzv5WkaQOwplsAYuzLn1cNRUKbWay5ClCSm6rsoHGfaagW4/wXk9TxqJhcdmNZ+eeAvNXAxJIeRvb82pwANlSJ658FBw2ov75p3Y6rjvc8CUPsxBXZkw3dzOgwTdjmJI9q+aD4GuVeGiq9MdyJDgXUjxlP2qEtcLJfvvF9q5Bnzy+hoAV+A5yHg0lR0VjsUem2+CdexuHb/LJLx4YVkSrCSyEELAsfyJTCYNLaMKrWKujelqtKwXy4H/rwzaja6IBP77gkisNI82bvnrzn/QsvnueGyWSu/Z2HC2M/d6WAQAl3Et9W6kOb7MK+NAmEMOTW7tzaxjD+lq8aOiLJYndrOYaymin5GLNk3F2iqZMkhMCRC2YcstNr61w=
  file:
  - remollbuild.log
  - remolltest.unit.log
  - remolltest.commit.log
  - remolltest.release.log
  - remolltest.unit.log.tar.gz
  - remolltest.unit.root.tar.gz
  - remolltest.unit.analysis.log.tar.gz
  - remolltest.unit.analysis.png.tar.gz
  - remolltest.unit.analysis.root.tar.gz
  - remolltest.commit.log.tar.gz
  - remolltest.commit.root.tar.gz
  - remolltest.commit.analysis.log.tar.gz
  - remolltest.commit.analysis.png.tar.gz
  - remolltest.commit.analysis.root.tar.gz
  - remolltest.release.log.tar.gz
  - remolltest.release.root.tar.gz
  - remolltest.release.analysis.log.tar.gz
  - remolltest.release.analysis.png.tar.gz
  - remolltest.release.analysis.root.tar.gz
  skip_cleanup: true
  on:
    repo: JeffersonLab/remoll
    tags: true

