name: Build Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: eic/setup-cvmfs@main
      - uses: eic/setup-spack@main
        with:
          environment: eic
      - name: Build
        run: |
          source ${SPACK_ROOT}/share/spack/setup-env.sh
          spack load root
          spack load geant4
          Geant4_DIR=`spack location -i geant4`
          Geant4_DIR=`find $Geant4_DIR -iname Geant4Config.cmake`
          Geant4_DIR=`dirname $Geant4_DIR`
          echo $Geant4_DIR
          mkdir build
          cmake -B build -DGeant4_DIR=$Geant4_DIR
          make -C build install
      - name: Test
        run: |
          build/remoll macros/runexample.mac
