name: Build Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: eic/setup-cvmfs@main
      - uses: eic/setup-spack@main
        with:
          environment: eic
      - name: Build
        run: |
          source ${SPACK_ROOT}/share/spack/setup-env.sh
          spack load root
          spack load geant4
          echo $CMAKE_PREFIX_PATH
          spack location -i geant4
          find `spack location -i geant4` -iname "Geant4Config.cmake"
          mkdir build && cmake -B build && make -C build install
      - name: Test
        run: |
          build/remoll macros/runexample.mac
