name: Build Docker Images

on:
  push:
    branches: [ develop ]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - 
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        tags: jeffersonlab/remoll:develop
        push: true
    -
      name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
  test_geometry:
    name: Geometry test suite ${{ matrix.suite }}
    strategy:
      matrix:
        suite: [validate,overlap]
    runs-on: ubuntu-latest
    container:
      image: docker://jeffersonlab/remoll:develop
    steps:
    - name: Geometry test suite ${{ matrix.suite }}
      run: |
        scripts/tests/test_geometries.sh ${{ matrix.suite }}
  test_running:
    name: Running test suite ${{ matrix.suite }}
    strategy:
      matrix:
        suite: [unit,commit]
    runs-on: ubuntu-latest
    container:
      image: docker://jeffersonlab/remoll:develop
    steps:
    - name: Geometry test suite ${{ matrix.suite }}
      run: |
        scripts/tests/test_macros.sh ${{ matrix.suite }}
